server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

application:
  client:
    openweathermap:
      api:
        url: https://api.openweathermap.org/data/2.5
        key: # key from https://home.openweathermap.org/api_keys
    weatherapi:
      api:
        url: https://api.weatherapi.com/v1
        key: # key from https://www.weatherapi.com/my
    weatherbit:
      api:
        url: https://api.weatherbit.io/v2.0
        key: # key from https://www.weatherbit.io/account/dashboard
